### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by omajid** [omajid/DotNetRegressionTestRunner#1]
I posted a quick summary of what the design of this project looks like here:

- [README](https://github.com/omajid/DotNetRegressionTestRunner/blob/master/README.md)
- [DESIGN](https://github.com/omajid/DotNetRegressionTestRunner/blob/master/DESIGN.md)

**Comment by omajid** [comment]
cc @tmds

**Comment by tmds** [comment]
Regarding

https://github.com/omajid/DotNetRegressionTestRunner/blob/04937770b4f45aa2c445c3dcf19ef61717796ed3/RedHat.DotNet.DotNetRegressionTestRunner/Test.cs#L23-L28

Perhaps to simplify this, we can require the test xml to be at the top of the file. And the first line needs to be `// <test>` and last `</test>`. Then we strip of the '// ' from each line and parse that xml.

e.g.
```
// some comment/copyright
// <test>
// <requires runtime=">2.0"/>
// </test>
// some more comment
using System;
...
```

**Comment by omajid** [comment]
That sounds like a great idea!

**Comment by omajid** [comment]
Implemented (partially, no xml parsing yet) in https://github.com/omajid/DotNetRegressionTestRunner/commit/b575ff2679b9c6e9bf32eef7e864e4655d73de2b

**Comment by omajid** [comment]
I just realized ` <requires runtime="<2.0"/>` is not valid xml :(

**Comment by omajid** [comment]
I implemented an alternate scheme with syntax like `[,2.0)` to indicate all versions up to (but not including) 2.0.
